thrust_to_pwm:
  topics/subscribers/thrust_body_request: "/controls/inner_loops_pid/thrust_body_request"
  topics/publishers/thrusters: "/mavros/rc/override"
  thrusters/allocation_vector: [1.0, 1.0, 1.0]
  thrusters/ctf: [0.0, 10.28, 1582]
  thrusters/ctb: [0.0, 12.28, 1482]