imu:
  node_frequency: 10
  topics/publishers: ["/measurement/orientation"]
  topics/subscribers: ["/mavros/imu/data"]
  frame_override: "ahrs"

pressure:
  node_frequency: 5
  topics/publishers: ["/measurement/position"]
  topics/subscribers: ["/mavros/imu/static_pressure"]
  frame_override: "depth"
  threshold: 10
  density: 997.0474

ardusub_thrust_allocation:
  topics/subscribers/thrust_body_request: "/controls/inner_loops_pid/thrust_body_request"
  topics/publishers/thrusters: "/mavros/rc/override"
  thrusters/allocation_vector: [1.0, 1.0, 1.0]
  thrusters/ctf: [0.0, 10.28, 1582]
  thrusters/ctb: [0.0, 12.28, 1482]

dvl:
  ip: 192.168.2.3
  port: 16171