plugin_blacklist:
- '*'
# common
- safety_area
# extras
- image_pub
- vibration
- distance_sensor
- rangefinder
- wheel_odometry

plugin_whitelist:
- 'imu*'
- state
- '*global_position/raw*'
# - vfr_hud
# - 'sys_*'
