auv_sim:

  # General simulation environment constants
  fluid_density: 1.025 # (kg/l)

  # Vehicle dynamic parameters
  vehicle:
    mass: 11.5 # (kg)
    zg: 0.02 # center of gravity in body axis (m)
    vehicle_density: 1.0 # TO DEFINE LATER
    inertia_tensor: [1000.0, 1000.0, 1000.0]  # diagonal (3x3) moment of inertia matrix (kg/m2) medusa
    # inertia_tensor: [1.6, 1.6, 1.6]  # diagonal (3x3) moment of inertia matrix (g/m2)   bluerov
    linear_damping_tensor: [-4.03, -6.22, -5.18, -0.07, -0.07, -0.07] # diagonal (6x6) matrix with linear damping
    quadratic_damping_tensor: [-18.18, -21.66, -36.99,  -1.55, -1.55, -1.55] # diagonal (6x6) matrix with quadratic damping
    added_mass_tensor: [5.5, 12.7, 14.57, 0.12, 0.12, 0.12] # diagonal (6x6) matrix with added mass terms

    actuators:
      # For each thruster [Fx, Fy, Fz, lx, ly, lz] where F = forces and l = moments arms
      # and each line of the matrix represents a thruster
      allocation_matrix: [1.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                          0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
                          0.0, 0.0, 1.0, 0.0, 0.0, 0.0,
                          0.707, 0.707, 0.0, 1.0, 1.0, 0.0,
                          0.707, 0.0, 0.707, 1.0, 0.0, 1.0,
                          0.0, 0.707, 0.707, 0.0, 1.0, 1.0]

      # Thrusters parameter
      lump_param_positive: [0.00000177778, 0.0, 0.0]  # (a*|x|^{2} + b*|x| + c)
      lump_param_negative: [-0.00000177778, 0.0, 0.0] # (a*|x|^{2} + b*|x| + c)

      max_input: 100 # Maximum normalized input value
      min_input: 8.6 # Minimum normalized input value (for values < |min_input|) the motors "won't" spin <-> dead-zone

      # A gain used to scale the applied normalized input thrust (in this case used to convert from % to RPM)
      # This gain is mainly used to convert between scales
      gain: 45

      # Model of each thruster is the same as for a regular DC motor (pole+delay)
      pole: 7.2115
      delay: 0.345 # s

  # Oceans currents as a gaussian process
  current:
    mean: [0.0, 0.0, 0.0]
    sigma: [0.0, 0.0, 0.0]
    minimum: [0.0, 0.0, 0.0]
    maximum: [0.0, 0.0, 0.0]

world_frame: "world"
base_link: "base_link"