auv_sim:

  # General simulation environment constants
  fluid_density: 1.025 # (kg/l)

  # Vehicle dynamic parameters
  vehicle:
    mass: 11.5 # (kg)
    zg: 0.02 # center of gravity in body axis (m)
    vehicle_density: 1.0 # TO DEFINE LATER
    inertia_tensor: [0.16, 0.16, 0.16]  # diagonal (3x3) moment of inertia matrix (kg/m2)
    linear_damping_tensor: [-4.03, -6.22, -5.18, -0.07, -0.07, -0.07] # diagonal (6x6) matrix with linear damping
    quadratic_damping_tensor: [-18.18, -21.66, -36.99,  -1.55, -1.55, -1.55] # diagonal (6x6) matrix with quadratic damping
    added_mass_tensor: [-5.5, -12.7, -14.57, -0.12, -0.12, -0.12] # diagonal (6x6) matrix with added mass terms

    actuators:
      # For each thruster [Fx, Fy, Fz, lx, ly, lz] where F = forces and l = moments arms
      # and each line of the matrix represents a thruster
      allocation_matrix: [1.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                          0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
                          0.0, 0.0, 1.0, 0.0, 0.0, 0.0,
                          0.707, 0.707, 0.0, 1.0, 1.0, 0.0,
                          0.707, 0.0, 0.707, 1.0, 0.0, 1.0,
                          0.0, 0.707, 0.707, 0.0, 1.0, 1.0]

      # Thrusters parameter
      lump_param_positive: [0.00004567165, -0.001457, 0.0674606]  # (a*|x|^{2} + b*|x| + c)
      # lump_param_positive: [0.00004567165, 0.0, 0.0]  # (a*|x|^{2} + b*|x| + c)
      lump_param_negative: [-0.000038676, 0.0020187, -0.11301426] # (a*|x|^{2} + b*|x| + c)
      # lump_param_negative: [-0.000038676, 0.0, 0.0] # (a*|x|^{2} + b*|x| + c)

      max_input: 350 # Maximum normalized input value
      min_input: 31.7 # Minimum normalized input value (for values < |min_input|) the motors "won't" spin <-> dead-zone

      # A gain used to scale the applied normalized input thrust (in this case used to convert from % to RPM)
      # This gain is mainly used to convert between scales
      gain: 10

      # Model of each thruster is the same as for a regular DC motor (pole+delay)
      pole: 7.2115
      delay: 0.345 # s

  # Oceans currents as a gaussian process
  current:
    mean: [0.0, 0.0, 0.0]
    sigma: [0.0, 0.0, 0.0]
    minimum: [0.0, 0.0, 0.0]
    maximum: [0.0, 0.0, 0.0]

world_frame: "world"
base_link: "base_link"

sensors:
    water_column: 100
    sensors:
        - type     : "GNSS"
          frame_id : "mblack_gnss"
          frequency: 10.0
          count    : 0        # After n measumerements sensor is discarded
          noise    : 0.00
          variance : 0.03
          debug    : true     # Full gps even when diving
        - type     : "DVL_BT"
          frame_id : "mblack_dvl_bt"
          frequency: 5.0
          noise    : 0.01
          variance : 0.05
          altitude : 30.0
          debug    : true     # works regardless of depth
          count    : 0
        - type     : "AHRS"
          frame_id : "mblack_ahrs"
          frequency: 5.0
          noise    : [0.051, 0.017]
          variance : 0.001
        - type     : "DEPTH"
          frame_id : "mblack_depth"
          frequency: 5.0
          noise    : 0.01
          variance : 0.005
          count    : 0        # After n measumerements sensor is discarded
        - type     : "MODEL"
          frequency: 10.0
