filter:
    tf:                         # TF publishers
        broadcast: true         # flag to publish TF
        frames: [               # <base_link, odom, map, world>
            "mblack_base_link", "null", "mblack_map", "mblack_map"
        ]
    kalman_filter:
        # reset filter if no measurement is received for a certain period (any measurement). 0 for no reset
        reset_period: 0
        
        # predict period
        predict_period: 0.1

        # Buffer for saving measurements while usbl fix is not received. (secs)
        save_measurement_interval: 1

        # outlier rejection threshold
        outlier_rejection_threshold: 15

        # process noise for position, velocity, angles, angle rate, acceleration, altitude
        process_covariance: [0.1, 0.2, 0.1, 0.1, 0.1, 0.1]   

        # outlier reject counters for position, velocity, angle, angle rate, acceleration, altitude  
        reject_counter:     [8, 200, 12, 4, 7, 6]              

        # ahrs an input(true) or measurement (false)
        bypass_ahrs: true 

        # If no frame_id ("" or "null"), the filter is initialized with the values defined here.
        # If a frame_id is given ("gnss") the initial position of the filter comes from the sensor.
        # Filter won't work without a initial position
        manually_initialization:
                frame_id: "gnss"
                value: [0.0, 0.0, -0.1,    # Position - x, y, z
                        0.0, 0, 0,                      # Velocity - dx, dy, dz
                        0, 0, 0,                        # Orientation - r, p, ya
                        0, 0, 0,                        # Orientation Rate - dr, dp, dya
                        0, 0, 5.0]                      # Acceleration & Altitude - ax, ay, A
                noise: [1.0, 1.0, 0.01,                 # Set the intial state covariance here
                        0.001 , 0.001 , 0.01 ,
                        0.02   , 0.03   , 0.04,
                        0.01 , 0.01 , 0.01 ,
                        0.0, 0.0, 0.01]
        
#NOTE: The real dvl give us 3 velocities (vx,vy, vz), but we are just using only the 2D velocities. To use the vz is necessary to change the sensorSplit method in FilterNode (in the next iterations of the code :) ). 
        sensors:
            -   frame_id:   "gnss"
                config:     "Hposition"            # [x, y]
                noise:      [0.001, 0.001]         # if you want to use the noise directly from the sensor, fill the noise with zeros
                outlier_tolerance: 2.0
                reject_counter: 2
            -   frame_id:   "vel_in"
                config:     "Hvelocity"            # [vx, vy]
                noise:      [0.0225, 0.0225]
                outlier_tolerance: 0.2
                reject_counter: 200
            -   frame_id:   "depth" 
                config:     "Vposition"            # [z]
                noise:      [0.1]
                outlier_tolerance: 0.2
                reject_counter: 8
            -   frame_id:   "imu"  
                config:     "orientation"          
                noise:      [0.05, 0.05, 0.05,  # [roll, pitch, yaw]
                            0.2, 0.2, 0.2]         # roll_rate, picth_rate, yaw_rate]
                outlier_tolerance: 0.5
                reject_counter: 12
    dvl:
      body_frame: true  # If dvl values are in inercial frame, you need to put false here!!!

usbl2pos:
    t_sync: 2
    # false, vehicle acts as an achor, estimates other vehicles position 
    # true, vehicle estimates its own position with respect to an anchor    
    fix_type: false
    meas_noise: 0.001